export const icon = {

     bed:require("../assets/image/bed.webp"),
     carImage:require("../assets/image/car.webp"),
     furnitureImage:require("../assets/image/furniture.webp"),
     houseImage:require("../assets/image/house.webp"),
     laptop:require("../assets/image/laptop.webp"),
     shooes:require("../assets/image/shooes.webp"),
     sale:require("../assets/image/sale.webp"),
     sale2:require("../assets/image/sale2.webp"),
     sale3:require("../assets/image/sale3.webp"),
     sale4:require("../assets/image/sale4.webp"),
     facebook:require("../assets/facebook.png"),
     google:require("../assets/google.png"),
     search:require("../assets/search.png"),
     car:require("../assets/car.png"),
     clothing:require("../assets/clothing.png"),
     education:require("../assets/education.png"),
     electronics:require("../assets/electronics.png"),
     furniture:require("../assets/furniture.png"),
     hobby:require("../assets/hobby.png"),
     job:require("../assets/job.png"),
     properties:require("../assets/properties.png"),
     plus:require("../assets/plus.png"),
     up:require("../assets/up.png"),
     down:require("../assets/down.png"),
}